### ISSUE TITLE
(Solution) Build with node +17.x  (ERR_OSSL_EVP_UNSUPPORTED)

### ISSUE THREAD

**Issue by Altffenser** [hulyak/a-to-z-coding-resources#51]
For build as espected in repository documentation with node 17.x or or higher (I have 18.5) just put this code fragment in `package.json` to build successfully.

`SET NODE_OPTIONS=--openssl-legacy-provider` 

It should look as follows.

`"start": "SET NODE_OPTIONS=--openssl-legacy-provider && docusaurus start",`

This solves problems with "digital envelope routines" and prevents the error in title.
```
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
library: 'digital envelope routines',
reason: 'unsupported',
code: 'ERR_OSSL_EVP_UNSUPPORTED'
```

**Comment by hulyak** [comment]
Thank you. I've merged the PR
